projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src
        region: us-east-1
        apiId: otmlwopxtrgtbdzgz7lgchbpqy
        frontend: javascript
        framework: vue
        maxDepth: 2
